
[build]
command = "remix build && cp _app_redirects public/_redirects"
publish = "public"


[dev]
command = "npm run dev"
targetPort = 3000

# [[redirects]]
# from = "/auth"
# to = "/"
# status = 200

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
