[build]
  command = "npm run build"
  publish = "public"

[context.production]
  environment = { NODE_VERSION = "18.18.2" }

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/auth"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
