const OneTwoFive = {
  id: "2a6cfd4c-185b-459f-9a8b-3525ee4776c2",
  createdAt: new Date("2022-08-04T19:56:29.131Z"),
  updatedAt: new Date("2022-08-04T19:56:29.132Z"),
  name: "OneDim TwoFive",
  description: "description test",
  sheet: [
    {
      bar: 0,
      beat: 0,
      note: ["C3", "E3", "G3", "B3"],
      root: "C",
      type: "maj",
      duration: "2n.",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 0,
      beat: 3,
      note: ["Db3", "Fb3", "Abb3", "Cbb4"],
      root: "Db",
      type: "dim",
      duration: "4n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 1,
      beat: 0,
      note: ["D3", "F3", "A3", "C4"],
      root: "D",
      type: "min",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 1,
      beat: 2,
      note: ["G2", "B2", "D3", "F3", "A3", "E4"],
      root: "G",
      type: "",
      duration: "2n",
      extension: "13",
      sixteenth: 0,
    },
  ],
  userId: "e4e34936-c4c6-4f70-83bd-217183f39e38",
  authorName: "dennis",
  bpm: 80,
  upvotes: 0,
};

const jazzBlues = {
  id: "5d0010a6-4a66-4085-8569-980738336ce1",
  createdAt: new Date("2022-08-05T20:12:37.456Z"),
  updatedAt: new Date("2022-08-05T20:12:37.457Z"),
  name: "Jazzy Blues in F",
  description: "F major Blues with a jazz twist",
  sheet: [
    {
      bar: 0,
      beat: 0,
      note: ["F3", "A3", "C4", "Eb4"],
      root: "F",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 1,
      beat: 0,
      note: ["Bb2", "D3", "F3", "Ab3"],
      root: "Bb",
      type: "",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 1,
      beat: 2,
      note: ["B2", "D3", "F3", "Ab3"],
      root: "B",
      type: "dim",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 2,
      beat: 0,
      note: ["F3", "A3", "C4", "Eb4"],
      root: "F",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 3,
      beat: 0,
      note: ["C3", "Eb3", "G3", "Bb3"],
      root: "C",
      type: "min",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 3,
      beat: 2,
      note: ["F3", "A3", "C4", "Eb4"],
      root: "F",
      type: "",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 4,
      beat: 0,
      note: ["Bb2", "D3", "F3", "Ab3"],
      root: "Bb",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 5,
      beat: 0,
      note: ["B2", "D3", "F3", "Ab3"],
      root: "B",
      type: "dim",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 6,
      beat: 0,
      note: ["F3", "A3", "C4", "Eb4"],
      root: "F",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 7,
      beat: 0,
      note: ["D3", "F#3", "A3", "C4"],
      root: "D",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 8,
      beat: 0,
      note: ["G2", "Bb2", "D3", "F3"],
      root: "G",
      type: "min",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 9,
      beat: 0,
      note: ["C3", "E3", "G3", "Bb3"],
      root: "C",
      type: "",
      duration: "1n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 10,
      beat: 0,
      note: ["F3", "A3", "C4", "Eb4"],
      root: "F",
      type: "",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 10,
      beat: 2,
      note: ["D3", "F#3", "A3", "C4"],
      root: "D",
      type: "",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 11,
      beat: 0,
      note: ["G2", "Bb2", "D3", "F3"],
      root: "G",
      type: "min",
      duration: "2n",
      extension: "7",
      sixteenth: 0,
    },
    {
      bar: 11,
      beat: 2,
      note: ["C3", "E3", "G3", "Bb3", "D4", "A4"],
      root: "C",
      type: "",
      duration: "2n",
      extension: "13",
      sixteenth: 0,
    },
  ],
  userId: "e4e34936-c4c6-4f70-83bd-217183f39e38",
  authorName: "dennis",
  bpm: 112,
  upvotes: 0,
};

export { OneTwoFive, jazzBlues };
